### ISSUE TITLE
Boringssl client and server error 

### ISSUE THREAD

**Issue by prchander** [open-quantum-safe/boringssl#42] opened 2020-11-14 19:24 UTC
Hello, I used a script in OpenSSL to generate a dilithium2 private key and certificate and I tested them with OpenSSL client and server where they were functional. In boringSSL, when I initiate the server, I get the following error:
Failed to load private key: key_srv.key
94525136107832:error:06000066:public key routines:OPENSSL_internal:DECODE_ERROR:../crypto/evp/p_oqs_asn1.c:257:
94525136107832:error:13000068:PKCS8 routines:OPENSSL_internal:DECODE_ERROR:../crypto/pkcs8/pkcs8_x509.c:128:
94525136107832:error:0900000c:PEM routines:OPENSSL_internal:ASN.1 encoding routines:../crypto/pem/pem_pkey.c:138:
94525136107832:error:10000009:SSL routines:OPENSSL_internal:PEM routines:../ssl/ssl_file.cc:487:

I have included my key and cert generation script and the boringssl client and server scripts. Please let me know where I am making an error.

Thank you
[boringssl files.zip](https://github.com/open-quantum-safe/boringssl/files/5541334/boringssl.files.zip)

**Comment by dstebila** [comment] 2020-11-18 03:27
Is this the same as @34?  If so please keep the discussion there so we don't make duplicate issues.

**Comment by prchander** [comment] 2020-11-18 07:58
So 34 can be solved as I have traced the error down to OpenSSL certs not working with BoringSSL server and client. I just added this issue because it provides more clarity for the issue. 

Thank you

**Comment by xvzcf** [comment] 2020-11-25 15:47
There are some bugs [here](https://github.com/open-quantum-safe/boringssl/blob/master/crypto/evp/p_oqs_asn1.c) that are most likely the root cause of this problem. I will aim to start working on a fix in 1-2 weeks.

**Comment by xvzcf** [comment] 2020-12-16 21:20
@prchander can you try [this branch](https://github.com/open-quantum-safe/boringssl/tree/fix-oqs-asn1) and see if it works? Note that the branch temporarily only supports Dilithium 2 certificates.

**Comment by prchander** [comment] 2020-12-17 03:28
Tied to build this branch. The build failed with the following:
FAILED: ssl/CMakeFiles/ssl.dir/ssl_key_share.cc.o
/usr/bin/c++  -DBORINGSSL_DISPATCH_TEST -DBORINGSSL_HAVE_LIBUNWIND -DBORINGSSL_IMPLEMENTATION -DBORINGSSL_SHARED_LIBRARY -DOQS_RUN_URANDOM_TESTS -Dssl_EXPORTS -I../third_party/googletest/include -I../ssl/../include -I../oqs/include -Werror -Wformat=2 -Wsign-compare -Wmissing-field-initializers -Wwrite-strings -Wvla -ggdb -Wall -fvisibility=hidden -fno-common -Wno-free-nonheap-object -Wimplicit-fallthrough -Wmissing-declarations -std=c++11 -fno-exceptions -fno-rtti -Wshadow -fPIC -MD -MT ssl/CMakeFiles/ssl.dir/ssl_key_share.cc.o -MF ssl/CMakeFiles/ssl.dir/ssl_key_share.cc.o.d -o ssl/CMakeFiles/ssl.dir/ssl_key_share.cc.o -c ../ssl/ssl_key_share.cc
../ssl/ssl_key_share.cc: In static member function ‘static bssl::UniquePtr<bssl::SSLKeyShare> bssl::SSLKeyShare::Create(uint16_t)’:
../ssl/ssl_key_share.cc:971:33: error: ‘OQS_KEM_alg_hqc_128’ was not declared in this scope; did you mean ‘OQS_KEM_alg_count’?
  971 |       if(OQS_KEM_alg_is_enabled(OQS_KEM_alg_hqc_128))
      |                                 ^~~~~~~~~~~~~~~~~~~
      |                                 OQS_KEM_alg_count
../ssl/ssl_key_share.cc:976:33: error: ‘OQS_KEM_alg_hqc_128’ was not declared in this scope; did you mean ‘OQS_KEM_alg_count’?
  976 |       if(OQS_KEM_alg_is_enabled(OQS_KEM_alg_hqc_128))
      |                                 ^~~~~~~~~~~~~~~~~~~
      |                                 OQS_KEM_alg_count
../ssl/ssl_key_share.cc:981:33: error: ‘OQS_KEM_alg_hqc_192’ was not declared in this scope; did you mean ‘OQS_KEM_alg_count’?
  981 |       if(OQS_KEM_alg_is_enabled(OQS_KEM_alg_hqc_192))
      |                                 ^~~~~~~~~~~~~~~~~~~
      |                                 OQS_KEM_alg_count
../ssl/ssl_key_share.cc:986:33: error: ‘OQS_KEM_alg_hqc_192’ was not declared in this scope; did you mean ‘OQS_KEM_alg_count’?
  986 |       if(OQS_KEM_alg_is_enabled(OQS_KEM_alg_hqc_192))
      |                                 ^~~~~~~~~~~~~~~~~~~
      |                                 OQS_KEM_alg_count
../ssl/ssl_key_share.cc:991:33: error: ‘OQS_KEM_alg_hqc_256’ was not declared in this scope; did you mean ‘OQS_KEM_alg_count’?
  991 |       if(OQS_KEM_alg_is_enabled(OQS_KEM_alg_hqc_256))
      |                                 ^~~~~~~~~~~~~~~~~~~
      |                                 OQS_KEM_alg_count
../ssl/ssl_key_share.cc:996:33: error: ‘OQS_KEM_alg_hqc_256’ was not declared in this scope; did you mean ‘OQS_KEM_alg_count’?
  996 |       if(OQS_KEM_alg_is_enabled(OQS_KEM_alg_hqc_256))
      |                                 ^~~~~~~~~~~~~~~~~~~
      |                                 OQS_KEM_alg_count
[374/447] Building CXX object ssl/CMakeFiles/ssl.dir/ssl_lib.cc.o
ninja: build stopped: subcommand failed.

**Comment by xvzcf** [comment] 2020-12-17 14:31
Did you pull in the latest liboqs?

**Comment by prchander** [comment] 2020-12-19 09:42
Reinstalled all libraries and I still get the same error. 
Failed to load private key: key_srv.pem
94834718447928:error:06000066:public key routines:OPENSSL_internal:DECODE_ERROR:../crypto/evp/p_oqs_asn1.c:257:
94834718447928:error:13000068:PKCS8 routines:OPENSSL_internal:DECODE_ERROR:../crypto/pkcs8/pkcs8_x509.c:128:
94834718447928:error:0900000c:PEM routines:OPENSSL_internal:ASN.1 encoding routines:../crypto/pem/pem_pkey.c:138:
94834718447928:error:10000009:SSL routines:OPENSSL_internal:PEM routines:../ssl/ssl_file.cc:487:

I am including the keys and certificates I used 
[Dilithium2.zip](https://github.com/open-quantum-safe/boringssl/files/5719157/Dilithium2.zip)

**Comment by xvzcf** [comment] 2020-12-21 14:38
Did you pull in the `fix-oqs-asn1` branch of BoringSSL?

**Comment by prchander** [comment] 2020-12-21 20:44
Yes. I reinstalled the libraries again just to make sure I was using the right libraries and yes I still am getting the same error. 
pi@pi:~/oqs/boringssl/test$ python3 server.py 
Failed to load private key: key_srv.pem
94768961079608:error:06000066:public key routines:OPENSSL_internal:DECODE_ERROR:../crypto/evp/p_oqs_asn1.c:257:
94768961079608:error:13000068:PKCS8 routines:OPENSSL_internal:DECODE_ERROR:../crypto/pkcs8/pkcs8_x509.c:128:
94768961079608:error:0900000c:PEM routines:OPENSSL_internal:ASN.1 encoding routines:../crypto/pem/pem_pkey.c:138:
94768961079608:error:10000009:SSL routines:OPENSSL_internal:PEM routines:../ssl/ssl_file.cc:487:
pi@pi:~/oqs/boringssl/test$

**Comment by prchander** [comment] 2020-12-22 01:24
I just reinstalled everything and I think I had forgotten to git checkout to the branch because I assumed the link was to the branch. Client and server works with Dilithium 2 certificates. Thank you for the help

**Comment by xvzcf** [comment] 2020-12-23 18:22
Fixed by https://github.com/open-quantum-safe/boringssl/pull/45

**Closed by xvzcf** 2020-12-23 18:22 UTC
